

use db_shinestock;

insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (2, now(), 'Alfinetes e Contrapinos', 'Acabamentos', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (1, now(), 'ABS', 'Acabamentos', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (3, now(), 'Arames', 'Acabamentos', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (4, now(), 'Argolas', 'Acabamentos', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (5, now(), 'Base de Brinco', 'Acabamentos', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (6, now(), 'Base de Maxi Colar', 'Acabamentos', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (7, now(), 'Cabides', 'Acabamentos', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (8, now(), 'Canecas', 'Acabamentos', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (9, now(), 'Contra argolas', 'Acabamentos', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (10, now(), 'Entremeios', 'Acabamentos', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (11, now(), 'Fechos', 'Acabamentos', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (12, now(), 'Fivelas', 'Acabamentos', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (13, now(), 'Fixador', 'Acabamentos', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (14, now(), 'Ponteiras', 'Acabamentos', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (15, now(), 'Spike Rebite', 'Acabamentos', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (16, now(), 'Tarraxas', 'Acabamentos', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (17, now(), 'Terminais', 'Acabamentos', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (18, now(), 'Terminal Amassar', 'Acabamentos', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (19, now(), 'Terminal Colagem', 'Acabamentos', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (20, now(), 'Tulipas', 'Acabamentos', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (21, now(), 'Corrente Ferro', 'Correntes', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (22, now(), 'Correntes Alumínio', 'Correntes', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (23, now(), 'Acetinado / Seda', 'Fios e Cordões', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (24, now(), 'Achatado 2 e 3mm', 'Fios e Cordões', 'N');select * from CmpMpr;
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (25, now(), 'Cabelo de Anjo', 'Fios e Cordões', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (26, now(), 'Cordão de camurça', 'Fios e Cordões', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (27, now(), 'Cordão de Pompom', 'Fios e Cordões', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (28, now(), 'Cordão de Strass / Gliter', 'Fios e Cordões', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (39, now(), 'Cordonê', 'Fios e Cordões', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (30, now(), 'Couro Ecológico', 'Fios e Cordões', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (31, now(), 'Couro Ecológico Trançado', 'Fios e Cordões', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (32, now(), 'Couro Ecológico Trançado Achatado', 'Fios e Cordões', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (33, now(), 'Couro Natural', 'Fios e Cordões', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (34, now(), 'Elásticos', 'Fios e Cordões', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (35, now(), 'Emborrachado', 'Fios e Cordões', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (36, now(), 'Encerado', 'Fios e Cordões', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (37, now(), 'Encerado Especial e Coreano', 'Fios e Cordões', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (38, now(), 'Fios de Juta', 'Fios e Cordões', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (39, now(), 'Nylon', 'Fios e Cordões', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (40, now(), 'Poliester', 'Fios e Cordões', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (41, now(), 'São Francisco', 'Fios e Cordões', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (42, now(), 'Silicone', 'Fios e Cordões', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (43, now(), 'Tiras de Couro Natural', 'Fios e Cordões', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (44, now(), 'Pedras em fio', 'Pedras', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (45, now(), 'Agata Pink', 'Pedras', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (46, now(), 'Ametista', 'Pedras', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (47, now(), 'Brown Glass', 'Pedras', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (48, now(), 'Cascalho de Pedra', 'Pedras', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (49, now(), 'Fashion White', 'Pedras', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (50, now(), 'Hematita', 'Pedras', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (51, now(), 'Howlita', 'Pedras', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (52, now(), 'Jaspe Madeira', 'Pedras', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (53, now(), 'Malasia', 'Pedras', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (54, now(), 'Olho de Tigre', 'Pedras', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (55, now(), 'Ônix', 'Pedras', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (56, now(), 'Pedras do Sol', 'Pedras', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (57, now(), 'Pingente de Pedra - Prisma', 'Pedras', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (58, now(), 'Quartzo Cherry', 'Pedras', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (59, now(), 'Quartzo Verde', 'Pedras', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (60, now(), 'Rubi Indiano', 'Pedras', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (61, now(), 'Turquesa', 'Pedras', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (62, now(), 'Vulcânica', 'Pedras', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (63, now(), 'Chatons', 'Strass', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (64, now(), 'Strass Acrílico', 'Strass', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (65, now(), 'Strass Chaton Autocolante', 'Strass', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (66, now(), 'Strass Chinês', 'Strass', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (67, now(), 'Strass em metro', 'Strass', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (68, now(), 'Strass Hotfix', 'Strass', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (69, now(), 'Strass Oktant Premium', 'Strass', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (70, now(), 'Strass Rivoli', 'Strass', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (71, now(), 'Strass Rivoli Swarovski', 'Strass', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (72, now(), 'Pingentes Fundição', 'Pingentes', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (73, now(), 'Pingentes Seda', 'Pingentes', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (74, now(), 'Meia Pérola', 'Pérolas', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (75, now(), 'Pérolas de abs', 'Pérolas', 'N');
insert into CmpMpr (CmpMprCod, CmpMprDca, CmpMprDsc, CmpMprObs, CmpMprBlq) values (76, now(), 'Pérolas de Vidro', 'Pérolas', 'N');

select * from CmpMpr;